<?php

namespace Database\Seeders;

use App\Models\Turma;
use Illuminate\Database\Seeder;

class TurmaSeeder extends Seeder
{
    public function run(): void
    {
        $turmas = [
            [
                'title' => 'Carreiras Policiais — base',
                'slug' => 'carreiras-policiais',
                'nome_publico' => 'Carreiras Policiais',
                'description' => 'Para quem já decidiu seguir a carreira policial e quer construir o núcleo de disciplinas presente nos principais concursos da área.',
                'grupo_exibicao' => Turma::GRUPO_BASE_CARREIRA,
                'categoria_navegacao' => 'Policiais',
                'termos_busca' => 'policial, polícia, PRF, PF, PM, PCDF',
                'secao_pagina' => 'Ainda está formando sua base?',
                'ordem_exibicao' => 1,
                'acao_principal' => Turma::ACAO_CHECKOUT,
                'checkout_url' => 'https://checkout.example.com/carreiras-policiais',
                'exibir_na_mentoria' => true,
                'destacar_turmas_abertas' => true,
            ],
            [
                'title' => 'Carreiras Administrativas — base',
                'slug' => 'carreiras-administrativas',
                'nome_publico' => 'Carreiras Administrativas',
                'description' => 'Para quem já escolheu a área administrativa e quer construir uma base aproveitável em diferentes órgãos e concursos.',
                'grupo_exibicao' => Turma::GRUPO_BASE_CARREIRA,
                'categoria_navegacao' => 'Administrativas',
                'termos_busca' => 'administrativa, analista, técnico, tribunais, legislativo',
                'secao_pagina' => 'Ainda está formando sua base?',
                'ordem_exibicao' => 2,
                'acao_principal' => Turma::ACAO_CHECKOUT,
                'checkout_url' => 'https://checkout.example.com/carreiras-administrativas',
                'exibir_na_mentoria' => true,
                'destacar_turmas_abertas' => true,
            ],
            [
                'title' => 'Núcleo duro para concursos',
                'slug' => 'nucleo-duro',
                'nome_publico' => 'Núcleo duro para concursos',
                'description' => 'Para quem ainda não definiu qual carreira seguir e quer começar pelas disciplinas mais cobradas em concursos, independentemente da área.',
                'grupo_exibicao' => Turma::GRUPO_BASE_GERAL,
                'categoria_navegacao' => 'Núcleo duro',
                'termos_busca' => 'núcleo duro, base, concursos, iniciante',
                'secao_pagina' => 'Ainda está formando sua base?',
                'ordem_exibicao' => 3,
                'acao_principal' => Turma::ACAO_CHECKOUT,
                'checkout_url' => 'https://checkout.example.com/nucleo-duro',
                'exibir_na_mentoria' => true,
                'destacar_turmas_abertas' => false,
            ],
            [
                'title' => 'PRF Policial 2026',
                'slug' => 'prf-policial',
                'nome_publico' => 'PRF — Policial',
                'description' => 'Preparação direcionada para o concurso de Policial da Polícia Rodoviária Federal.',
                'grupo_exibicao' => Turma::GRUPO_TURMA_DIRECIONADA,
                'categoria_navegacao' => 'Policiais',
                'orgao' => 'PRF',
                'cargo' => 'Policial',
                'termos_busca' => 'PRF, Polícia Rodoviária Federal, Policial PRF',
                'momento_concurso' => 'previsto',
                'exibir_momento_concurso' => true,
                'secao_pagina' => 'Já tem um concurso ou carreira como alvo?',
                'ordem_exibicao' => 10,
                'acao_principal' => Turma::ACAO_CHECKOUT,
                'checkout_url' => 'https://checkout.example.com/prf',
                'texto_cta' => 'COMEÇAR AGORA',
                'exibir_na_mentoria' => true,
                'destacar_turmas_abertas' => true,
                'plano_pronto_tutory' => true,
            ],
            [
                'title' => 'ABIN 2026',
                'slug' => 'abin',
                'nome_publico' => 'ABIN',
                'description' => 'Preparação específica para quem pretende direcionar os estudos para os próximos concursos da ABIN.',
                'grupo_exibicao' => Turma::GRUPO_TURMA_DIRECIONADA,
                'categoria_navegacao' => 'Inteligência',
                'orgao' => 'ABIN',
                'termos_busca' => 'ABIN, agência brasileira de inteligência',
                'momento_concurso' => 'previsto',
                'exibir_momento_concurso' => true,
                'secao_pagina' => 'Já tem um concurso ou carreira como alvo?',
                'ordem_exibicao' => 11,
                'acao_principal' => Turma::ACAO_CHECKOUT,
                'checkout_url' => 'https://checkout.example.com/abin',
                'exibir_na_mentoria' => true,
                'destacar_turmas_abertas' => true,
            ],
            [
                'title' => 'PMDF Praça 2026',
                'slug' => 'pmdf-praca',
                'nome_publico' => 'PMDF — Praça',
                'description' => 'Preparação direcionada para o próximo concurso de Praça da Polícia Militar do Distrito Federal.',
                'grupo_exibicao' => Turma::GRUPO_TURMA_DIRECIONADA,
                'categoria_navegacao' => 'Policiais',
                'orgao' => 'PMDF',
                'cargo' => 'Praça',
                'termos_busca' => 'PMDF, Polícia Militar do Distrito Federal, Praça PMDF',
                'momento_concurso' => 'edital_iminente',
                'exibir_momento_concurso' => true,
                'secao_pagina' => 'Já tem um concurso ou carreira como alvo?',
                'ordem_exibicao' => 12,
                'acao_principal' => Turma::ACAO_CHECKOUT,
                'checkout_url' => 'https://checkout.example.com/pmdf',
                'exibir_na_mentoria' => true,
                'destacar_turmas_abertas' => true,
                'plano_pronto_tutory' => true,
            ],
            [
                'title' => 'PMSC Praça 2026',
                'slug' => 'pmsc-praca',
                'nome_publico' => 'PMSC — Praça',
                'description' => 'Preparação direcionada para o próximo concurso de Praça da Polícia Militar de Santa Catarina.',
                'grupo_exibicao' => Turma::GRUPO_TURMA_DIRECIONADA,
                'categoria_navegacao' => 'Policiais',
                'orgao' => 'PMSC',
                'cargo' => 'Praça',
                'termos_busca' => 'PMSC, Polícia Militar de Santa Catarina',
                'momento_concurso' => 'previsto',
                'exibir_momento_concurso' => true,
                'secao_pagina' => 'Já tem um concurso ou carreira como alvo?',
                'ordem_exibicao' => 13,
                'acao_principal' => Turma::ACAO_WHATSAPP,
                'whatsapp_url' => 'https://wa.me/5561999999999',
                'aceitar_novos_alunos' => false,
                'exibir_na_mentoria' => false,
                'destacar_turmas_abertas' => true,
            ],
            [
                'title' => 'PCDF Agente de Custódia',
                'slug' => 'pcdf-agente-custodia',
                'nome_publico' => 'PCDF — Agente de Custódia',
                'description' => 'Preparação direcionada para o cargo de Agente de Custódia da PCDF.',
                'grupo_exibicao' => Turma::GRUPO_TURMA_DIRECIONADA,
                'categoria_navegacao' => 'Policiais',
                'orgao' => 'PCDF',
                'cargo' => 'Agente de Custódia',
                'termos_busca' => 'PCDF, Agente de Custódia, Polícia Civil DF',
                'momento_concurso' => 'previsto',
                'exibir_momento_concurso' => true,
                'secao_pagina' => 'Já tem um concurso ou carreira como alvo?',
                'ordem_exibicao' => 14,
                'acao_principal' => Turma::ACAO_LISTA,
                'interesse_url' => 'https://example.com/lista-pcdf',
                'whatsapp_url' => 'https://wa.me/5561999999999',
                'exibir_na_mentoria' => false,
                'destacar_turmas_abertas' => true,
            ],
            [
                'title' => 'Analista Judiciário — Tribunais',
                'slug' => 'analista-judiciario-tribunais',
                'nome_publico' => 'Analista Judiciário — Tribunais',
                'description' => 'Preparação para Analista Judiciário em tribunais, com direcionamento específico para o concurso.',
                'grupo_exibicao' => Turma::GRUPO_TURMA_DIRECIONADA,
                'categoria_navegacao' => 'Tribunais',
                'cargo' => 'Analista Judiciário',
                'termos_busca' => 'Analista Judiciário, TRF, TRE, tribunais',
                'momento_concurso' => 'edital_publicado',
                'exibir_momento_concurso' => true,
                'secao_pagina' => 'Já tem um concurso ou carreira como alvo?',
                'ordem_exibicao' => 15,
                'acao_principal' => Turma::ACAO_CHECKOUT,
                'checkout_url' => 'https://checkout.example.com/analista-judiciario',
                'popup_opcoes' => [
                    ['label' => 'Analista Judiciário', 'url' => 'https://checkout.example.com/analista'],
                    ['label' => 'Técnico Judiciário', 'url' => 'https://checkout.example.com/tecnico'],
                ],
                'texto_cta' => 'GARANTIR MINHA VAGA',
                'exibir_na_mentoria' => true,
                'destacar_turmas_abertas' => true,
                'plano_pronto_tutory' => true,
            ],
        ];

        foreach ($turmas as $turma) {
            Turma::updateOrCreate(
                ['slug' => $turma['slug']],
                array_merge([
                    'ativo' => true,
                    'exibir_no_site' => true,
                    'aceitar_novos_alunos' => $turma['aceitar_novos_alunos'] ?? true,
                    'available_slots' => 40,
                ], $turma)
            );
        }
    }
}
